[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      status = "200"

[build]
  command = "yarn && yarn build"